/**
 * Vital Synth Preset Generator (Curated Presets)
 *
 * Builds .vital preset files from curated preset definitions + user tuning overrides.
 * Replaces the old dynamic analysis-based generator.
 */

import vitalInitTemplate from '../data/vitalInitTemplate.json';
import { CURATED_PRESETS, TUNING_PARAMS, applyKickLFOEnvelopes } from '../data/vitalPresets';

/**
 * Sanitize a string for use in filenames — keeps spaces, letters, numbers, hyphens, parentheses.
 * Strips characters that are unsafe in file systems (slashes, colons, quotes, etc.).
 */
function sanitizeFilename(str) {
  return str.replace(/[<>:"/\\|?*]/g, '').replace(/\s+/g, ' ').trim();
}

/**
 * Build a clean, professional download filename for a Vital preset.
 *
 * Format examples:
 *   "SoundSauce - My Song (Bass - Sub Bass).vital"
 *   "SoundSauce - Warm Pad.vital"  (when no audio title or instrument)
 *
 * @param {Object} options
 * @param {string} [options.audioTitle] - Name of the uploaded audio file
 * @param {string} [options.instrument] - Detected instrument (e.g. 'bass', 'lead', 'pad')
 * @param {string} [options.presetName] - Name of the curated preset (e.g. 'Sub Bass', 'Warm Pad')
 * @returns {string} Clean filename without extension
 */
export function buildPresetFilename({ audioTitle, instrument, presetName } = {}) {
  // Strip file extension from audio title if present
  const cleanTitle = audioTitle ? audioTitle.replace(/\.(wav|mp3|m4a|flac|ogg|aac|webm)$/i, '').trim() : '';

  // Build the detail part: "Instrument - PresetName" or just one
  const instrumentLabel = instrument || '';
  const parts = [instrumentLabel, presetName].filter(Boolean);
  const detail = parts.length > 0 ? parts.join(' - ') : '';

  if (cleanTitle && detail) {
    return sanitizeFilename(`SoundSauce - ${cleanTitle} (${detail})`);
  } else if (cleanTitle) {
    return sanitizeFilename(`SoundSauce - ${cleanTitle}`);
  } else if (detail) {
    return sanitizeFilename(`SoundSauce - ${detail}`);
  }
  return 'SoundSauce Preset';
}

/**
 * Build a Vital preset from a curated preset ID + optional tuning overrides.
 *
 * @param {string} presetId - ID of the curated preset (e.g. 'saw_bass', 'warm_pad')
 * @param {Object} tuningOverrides - User slider values: { filter_cutoff: 80, attack: 0.5, ... }
 * @param {Object} metadata - Optional metadata: { presetName, author, audioTitle, instrument }
 * @returns {Object} Complete Vital preset object ready for export
 */
export function buildVitalPreset(presetId, tuningOverrides = {}, metadata = {}) {
  // 1. Find curated preset
  const curated = CURATED_PRESETS.find(p => p.id === presetId);
  if (!curated) {
    // Fallback to first preset (sub_bass) if unknown ID
    return buildVitalPreset('sub_bass', tuningOverrides, metadata);
  }

  // 2. Deep-clone Vital init template
  const preset = JSON.parse(JSON.stringify(vitalInitTemplate));

  // 3. Spread curated preset settings onto clone
  for (const [key, value] of Object.entries(curated.settings)) {
    preset.settings[key] = value;
  }

  // 4. Apply kick LFO envelopes if needed
  if (curated.postProcess === 'kick') {
    applyKickLFOEnvelopes(preset);
  }

  // 5. Apply tuning overrides from user sliders
  for (const [paramId, value] of Object.entries(tuningOverrides)) {
    const paramDef = TUNING_PARAMS.find(p => p.id === paramId);
    if (!paramDef) continue;

    // Clamp value to param range
    const clamped = Math.min(paramDef.max, Math.max(paramDef.min, value));
    preset.settings[paramDef.vitalKey] = clamped;

    // Handle linked toggles (reverb/chorus: dry_wet > 0 → _on = 1)
    if (paramDef.linkedToggle) {
      preset.settings[paramDef.linkedToggle] = clamped > 0 ? 1.0 : 0.0;
    }
  }

  // 6. Set metadata — shows inside Vital's preset browser
  const audioTitle = metadata.audioTitle ? metadata.audioTitle.replace(/\.(wav|mp3|m4a|flac|ogg|aac|webm)$/i, '').trim() : '';
  const instrumentName = metadata.instrument || '';

  // preset_name: shown in Vital's top bar and preset browser
  if (audioTitle && instrumentName) {
    preset.preset_name = `${audioTitle} (${instrumentName} - ${curated.name})`;
  } else if (audioTitle) {
    preset.preset_name = `${audioTitle} - ${curated.name}`;
  } else {
    preset.preset_name = metadata.presetName || curated.name || 'SoundSauce Export';
  }

  preset.author = metadata.author || 'SoundSauce';
  preset.preset_style = curated.category || '';

  // comments: shown in Vital's preset info section
  const commentParts = [`Preset: ${curated.name}`];
  if (audioTitle) commentParts.push(`Source: ${audioTitle}`);
  if (instrumentName) commentParts.push(`Instrument: ${instrumentName}`);
  commentParts.push('Generated by SoundSauce (soundsauce.app)');
  preset.comments = commentParts.join(' | ');

  return preset;
}

/**
 * Convert preset object to downloadable .vital file content.
 */
export function presetToVitalFile(preset) {
  return JSON.stringify(preset);
}

/**
 * Trigger download of a .vital preset file.
 *
 * @param {Object} preset - Complete Vital preset object
 * @param {string} [filename='SoundSauce Preset'] - Download filename (without extension)
 */
export function downloadVitalPreset(preset, filename = 'SoundSauce Preset') {
  const content = presetToVitalFile(preset);
  const blob = new Blob([content], { type: 'application/json' });
  const url = URL.createObjectURL(blob);

  const safeName = sanitizeFilename(filename) || 'SoundSauce Preset';
  const a = document.createElement('a');
  a.href = url;
  a.download = `${safeName}.vital`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Download a .vital preset from a remote URL (e.g. Vercel Blob).
 * Fetches the file content, optionally patches metadata for a professional
 * in-Vital display, and triggers a client-side download.
 *
 * @param {string} url - Remote URL of the .vital preset
 * @param {string} [filename='SoundSauce Preset'] - Download filename (without extension)
 * @param {Object} [patchMeta] - Optional metadata to patch into the preset JSON
 * @param {string} [patchMeta.preset_name] - Override preset_name shown in Vital
 * @param {string} [patchMeta.author] - Override author shown in Vital
 * @param {string} [patchMeta.comments] - Override comments shown in Vital
 */
export async function downloadRemotePreset(url, filename = 'SoundSauce Preset', patchMeta = null) {
  const response = await fetch(url);
  let text = await response.text();

  // Optionally patch metadata into the preset JSON for professional Vital display
  if (patchMeta) {
    try {
      const presetObj = JSON.parse(text);
      if (patchMeta.preset_name) presetObj.preset_name = patchMeta.preset_name;
      if (patchMeta.author) presetObj.author = patchMeta.author;
      if (patchMeta.comments) presetObj.comments = patchMeta.comments;
      text = JSON.stringify(presetObj);
    } catch {
      // If not valid JSON, download as-is
    }
  }

  const blob = new Blob([text], { type: 'application/octet-stream' });
  const blobUrl = URL.createObjectURL(blob);

  const safeName = sanitizeFilename(filename) || 'SoundSauce Preset';
  const a = document.createElement('a');
  a.href = blobUrl;
  a.download = `${safeName}.vital`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(blobUrl);
}

export default {
  buildVitalPreset,
  buildPresetFilename,
  presetToVitalFile,
  downloadVitalPreset,
};
